name: chocopathy
favicon: null
layout_spectrum: 0.5359917688183486
typography_spectrum: 0.8523768978193402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.40047876280732453
  lightness: 0.6530536420177668
  saturation: 0.5233168196864426
  rhythmicContrast: 0.5568692821543664
purpose: []
